[window]
decorations="None"
dimensions.columns=158
dimensions.lines=56
position.x=506

[font]
size=13.0
[font.bold]
family="DroidSansM Nerd Font Mono"
style="Bold"
[font.bold_italic]
family="DroidSansM Nerd Font Mono"
style="Bold Italic"
[font.italic]
family="DroidSansM Nerd Font Mono"
style="Italic"
[font.normal]
family="DroidSansM Nerd Font Mono"
style="Regular"

