[libraries]
#std.files = [
  #'/home/chris/vhdl_ls/vhdl_libraries/std/*.vhd',
#]
#ieee.files = [
  #'/home/chris/vhdl_ls/vhdl_libraries/ieee2008/*.vhdl',
  #'/home/chris/vhdl_ls/vhdl_libraries/synopsys/*.vhdl',
  #'/home/chris/vhdl_ls/vhdl_libraries/vital2000/*.vhdl',
#]
lib1.files = [
  '/home/chris/repo/x_rust_start_delete_me/stuff.vhd',
]
